"""
TaskState Repository — CRUD operations for TaskState model.

Only this file (and other files in database/) may import TaskState directly.
All services that need task state data MUST use this repository.
"""

from typing import Optional, Dict

import json

from sqlalchemy import select, delete as sql_delete, and_, update, case
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models import TaskState

from app.core.logging import get_logger
from app.core.task_status import (
    STATUS_AWAITING_INPUT,
    STATUS_INTERACTION_CONSUMING,
    STATUS_INTERACTION_FAILED,
    STATUS_CANCELLED,
    STATUS_CANCELLING,
    STATUS_COMPLETED,
    STATUS_FAILED,
    STATUS_QUEUED,
    STATUS_RUNNING,
)
from app.core.utils import utcnow

logger = get_logger(__name__)

def _utcnow_iso() -> str:
    """SQLite-compatible ISO timestamp for String-column storage.

    Uses space separator (``2026-05-28 12:00:00``) so SQLite string
    comparison with ``datetime('now', ...)`` works correctly.
    """
    return utcnow().strftime('%Y-%m-%d %H:%M:%S')


class TaskStateRepository:
    """Repository for TaskState table operations."""

    def __init__(self, session: AsyncSession):
        self._session = session

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def set_queued(
        self,
        task_id: str,
        task_type: str = "llm",
        session_id: str = "",
        owner_type: str = "chat_session",
        owner_id: str = "",
    ) -> None:
        """Insert a new queued task row.

        The ``task_id`` is freshly generated by every caller, so the insert
        never conflicts on the primary key. A conflict on the partial unique
        indexes (at most one runnable row or one interaction checkpoint per
        owner) surfaces as ``IntegrityError`` — callers use it to arbitrate
        concurrent claims. Interaction state is not set here; it is parked
        later by ``mark_awaiting_input``.
        """
        now = _utcnow_iso()
        resolved_owner_id = owner_id or session_id or None
        stmt = sqlite_insert(TaskState).values(
            task_id=task_id,
            session_id=session_id or None,
            owner_type=owner_type,
            owner_id=resolved_owner_id,
            status=STATUS_QUEUED,
            task_type=task_type,
            error=None,
            interaction_state=None,
            created_at=now,
            updated_at=now,
        )
        await self._session.execute(stmt)
        await self._session.commit()  # Required: raw execute() doesn't auto-commit in async sessions

    async def cancel_for_sessions(
        self, session_ids: list[str], *, commit: bool = True,
    ) -> list[str]:
        """Durably cancel every active task belonging to the sessions.

        Runnable rows become ``cancelling`` so a live runner can wind down;
        parked interaction rows become terminal immediately because they have
        no runner. The update is guarded and idempotent.
        """
        if not session_ids:
            return []
        result = await self._session.execute(
            select(TaskState.task_id).where(
                TaskState.session_id.in_(session_ids),
                TaskState.status.in_((
                    STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING,
                    STATUS_AWAITING_INPUT, STATUS_INTERACTION_CONSUMING,
                    STATUS_INTERACTION_FAILED,
                )),
            )
        )
        task_ids = list(result.scalars().all())
        now = _utcnow_iso()
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.session_id.in_(session_ids),
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING)),
            )
            .values(status=STATUS_CANCELLING, updated_at=now)
        )
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.session_id.in_(session_ids),
                TaskState.status.in_((
                    STATUS_AWAITING_INPUT, STATUS_INTERACTION_CONSUMING,
                    STATUS_INTERACTION_FAILED,
                )),
            )
            .values(
                status=STATUS_CANCELLED,
                interaction_state=None,
                updated_at=now,
            )
        )
        if commit:
            await self._session.commit()
        return task_ids

    async def mark_completed(self, task_id: str) -> None:
        """Mark a runnable task completed.

        Guarded UPDATE out of any runnable status (queued, running, or
        cancelling); tasks paused for input or already terminal are left
        untouched. The caller owns the completion decision and only reaches
        here after its checks fixed the outcome as completed, so the write
        records exactly the terminal state the subscriber saw.
        """
        now = _utcnow_iso()
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING)),
            )
            .values(
                status=STATUS_COMPLETED,
                updated_at=now,
            )
        )
        await self._session.commit()

    async def mark_failed(self, task_id: str, error: str) -> None:
        """Mark a task failed, honoring a cancel requested mid-run.

        Guarded UPDATE: a cancelling task finalizes as cancelled with no error
        surfaced, since the failure is a side effect of winding down. The WHERE
        predicate also protects terminal/input-paused tasks from a stale late
        write (the previous unguarded form could clobber any status).
        """
        now = _utcnow_iso()
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING)),
            )
            .values(
                status=case(
                    (TaskState.status == STATUS_CANCELLING, STATUS_CANCELLED),
                    else_=STATUS_FAILED,
                ),
                error=case(
                    (TaskState.status == STATUS_CANCELLING, None),
                    else_=error,
                ),
                updated_at=now,
            )
        )
        await self._session.commit()

    async def mark_cancelled(self, task_id: str) -> None:
        """Finalize an active task as cancelled.

        Used by the task runtime when a run ends in cancellation: the runner
        observed the cancelled terminal frame (or a hard cancel), and the
        durable row must match what subscribers saw whether or not the cancel
        intent was durably recorded first. Guarded UPDATE out of any runnable
        status; terminal and input-paused rows are left untouched, and any
        parked interaction state is cleared.
        """
        now = _utcnow_iso()
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING)),
            )
            .values(
                status=STATUS_CANCELLED,
                interaction_state=None,
                updated_at=now,
            )
        )
        await self._session.commit()

    async def mark_running(self, task_id: str) -> bool:
        """Explicit queued-to-running transition point for the task runtime.

        Guarded UPDATE: only a queued row is promoted, refreshing
        ``updated_at`` in the same write. The status predicate keeps a
        concurrent cancel or finalize write authoritative over this
        transition.
        """
        now = _utcnow_iso()
        result = await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status == STATUS_QUEUED,
            )
            .values(
                status=STATUS_RUNNING,
                updated_at=now,
            )
        )
        await self._session.commit()
        return bool(result.rowcount)

    async def fail_all_runnable(self, error: str) -> Dict[str, int]:
        """Finalize every runnable task of the project as failed or cancelled.

        Used by startup reconciliation for rows left active by a run that did
        not survive a process restart. Cancelling rows are finalized as
        cancelled with no error — the same cancel-aware mapping
            ``mark_failed`` applies, so a recorded cancel intent is never erased
            by the sweep. Interaction states are deliberately not in the
            predicate: their checkpoints must survive a restart so the user
            can resume or retry them. Returns ``{"failed": n, "cancelled": n}``.
        """
        now = _utcnow_iso()
        failed_result = await self._session.execute(
            update(TaskState)
            .where(TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING)))
            .values(
                status=STATUS_FAILED,
                error=error,
                updated_at=now,
            )
        )
        cancelled_result = await self._session.execute(
            update(TaskState)
            .where(TaskState.status == STATUS_CANCELLING)
            .values(
                status=STATUS_CANCELLED,
                interaction_state=None,
                updated_at=now,
            )
        )
        await self._session.commit()
        return {
            "failed": failed_result.rowcount,
            "cancelled": cancelled_result.rowcount,
        }

    async def get_stale_runnable(self, cutoff: str) -> list[Dict]:
        """Return runnable rows whose ``updated_at`` predates ``cutoff``.

        The runnable set is queued/running/cancelling; interaction checkpoints
        are never returned. Timestamps are the space-separated
        ISO strings written by every transition, so string comparison is
        correct. The task runtime uses this to find rows whose runner
        disappeared without finalizing them.
        """
        result = await self._session.execute(
            select(TaskState)
            .where(
                TaskState.status.in_(
                    (STATUS_QUEUED, STATUS_RUNNING, STATUS_CANCELLING),
                ),
                TaskState.updated_at < cutoff,
            )
            .order_by(TaskState.updated_at.asc())
        )
        return [self._to_dict(task) for task in result.scalars().all()]

    async def request_cancel(self, task_id: str) -> str:
        """Record cancel intent and return the resulting effective status.

        Two guarded UPDATEs committed together:
          * queued/running -> cancelling: the worker will wind the current
            step down and finalize as cancelled.
          * awaiting_input -> cancelled: the worker has already exited, so go
            straight to terminal and clear the parked interaction state.

        Idempotent: re-cancelling an already cancelling or terminal task
        returns its current status with no side effect. Returns ``"not_found"``
        if no such task exists.
        """
        now = _utcnow_iso()
        update_result = await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING)),
            )
            .values(status=STATUS_CANCELLING, updated_at=now)
        )
        if update_result.rowcount == 0:
            await self._session.execute(
                update(TaskState)
                .where(
                    TaskState.task_id == task_id,
                    TaskState.status.in_((STATUS_AWAITING_INPUT, STATUS_INTERACTION_CONSUMING, STATUS_INTERACTION_FAILED)),
                )
                .values(
                    status=STATUS_CANCELLED,
                    interaction_state=None,
                    updated_at=now,
                )
            )
        await self._session.commit()

        status_result = await self._session.execute(
            select(TaskState.status).where(TaskState.task_id == task_id)
        )
        status = status_result.scalar_one_or_none()
        return status if status is not None else "not_found"

    async def get_status(self, task_id: str) -> Optional[str]:
        """Return the raw persisted status for a task, or None if no row exists."""
        result = await self._session.execute(
            select(TaskState.status).where(TaskState.task_id == task_id)
        )
        return result.scalar_one_or_none()

    async def mark_awaiting_input(self, task_id: str, interaction_state: dict) -> None:
        """Park a task to await user input, unless it was cancelled mid-run.

        Guarded UPDATE: only transitions from queued/running, so a cancel that
        lands while an interactive tool is preparing its pause is honored
        rather than overwritten back to awaiting_input.
        """
        now = _utcnow_iso()
        await self._session.execute(
            update(TaskState)
            .where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_QUEUED, STATUS_RUNNING)),
            )
            .values(
                status=STATUS_AWAITING_INPUT,
                interaction_state=json.dumps(interaction_state, ensure_ascii=False),
                updated_at=now,
            )
        )
        await self._session.commit()

    async def claim_interaction(
        self, task_id: str, interaction_id: str, interaction_type: str,
    ) -> Optional[dict]:
        """Consume exactly one checkpoint identified by its durable identity.

        The select plus guarded update is a compare-and-swap: a duplicate,
        old, or concurrently consumed response cannot select another task in
        the same session and can never execute a tool twice.
        """
        result = await self._session.execute(
            select(TaskState).where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_AWAITING_INPUT, STATUS_INTERACTION_FAILED)),
                TaskState.interaction_state.isnot(None),
            )
        )
        task = result.scalar_one_or_none()
        if not task:
            return None
        state = self._parse_json(task.interaction_state)
        identity = state.get("checkpoint", {})
        if (
            identity.get("interaction_id") != interaction_id
            or identity.get("interaction_type") != interaction_type
        ):
            return None
        consumed = await self._session.execute(
            update(TaskState).where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_AWAITING_INPUT, STATUS_INTERACTION_FAILED)),
                TaskState.interaction_state == task.interaction_state,
            ).values(
                status=STATUS_INTERACTION_CONSUMING,
                updated_at=_utcnow_iso(),
            )
        )
        await self._session.commit()
        return state if consumed.rowcount == 1 else None

    async def complete_interaction(self, task_id: str) -> bool:
        result = await self._session.execute(
            update(TaskState).where(
                TaskState.task_id == task_id,
                TaskState.status == STATUS_INTERACTION_CONSUMING,
            ).values(
                status=STATUS_COMPLETED,
                interaction_state=None,
                updated_at=_utcnow_iso(),
            )
        )
        await self._session.commit()
        return result.rowcount == 1

    async def fail_interaction(self, task_id: str, error: str) -> bool:
        result = await self._session.execute(
            update(TaskState).where(
                TaskState.task_id == task_id,
                TaskState.status == STATUS_INTERACTION_CONSUMING,
            ).values(
                status=STATUS_INTERACTION_FAILED,
                error=error,
                updated_at=_utcnow_iso(),
            )
        )
        await self._session.commit()
        return result.rowcount == 1

    async def fail_consuming_interactions(self, error: str) -> int:
        """Make a crash between claim and completion visible and recoverable."""
        result = await self._session.execute(
            update(TaskState).where(
                TaskState.status == STATUS_INTERACTION_CONSUMING,
            ).values(
                status=STATUS_INTERACTION_FAILED,
                error=error,
                updated_at=_utcnow_iso(),
            )
        )
        await self._session.commit()
        return result.rowcount

    async def get_pending_interaction(
        self, task_id: str, interaction_id: str, interaction_type: str,
    ) -> Optional[dict]:
        """Read one pending checkpoint without falling back to its session."""
        result = await self._session.execute(
            select(TaskState).where(
                TaskState.task_id == task_id,
                TaskState.status.in_((STATUS_AWAITING_INPUT, STATUS_INTERACTION_FAILED)),
                TaskState.interaction_state.isnot(None),
            )
        )
        task = result.scalar_one_or_none()
        if not task:
            return None
        state = self._parse_json(task.interaction_state)
        identity = state.get("checkpoint", {})
        if identity.get("interaction_id") != interaction_id or identity.get("interaction_type") != interaction_type:
            return None
        return {**state, "task_id": task.task_id, "session_id": task.session_id}

    async def prune_terminal_by_session(self, session_id: str, keep: int = 5) -> int:
        """Delete terminal rows for a chat session, keeping the most recent *keep*."""
        return await self.prune_terminal_by_owner("chat_session", session_id, keep=keep)

    async def prune_terminal_by_owner(self, owner_type: str, owner_id: str, keep: int = 5) -> int:
        """Delete terminal rows for one owner, keeping the most recent *keep*.

        Every submission inserts a row and nothing reads an owner's terminal
        history, so claims prune as they go; a few rows stay for debugging.
        Awaiting_input rows (parked checkpoints) are never terminal and are
        never touched.
        """
        oldest_kept = (
            select(TaskState.task_id)
            .where(
                TaskState.owner_type == owner_type,
                TaskState.owner_id == owner_id,
                TaskState.status.in_(
                    (STATUS_COMPLETED, STATUS_FAILED, STATUS_CANCELLED)
                ),
            )
            .order_by(TaskState.created_at.desc(), TaskState.updated_at.desc())
            .offset(keep)
        )
        result = await self._session.execute(
            sql_delete(TaskState).where(TaskState.task_id.in_(oldest_kept))
        )
        await self._session.commit()
        return result.rowcount

    async def delete_by_owner(self, owner_type: str, owner_id: str) -> int:
        """Delete every task state row for a logical owner, any status."""
        result = await self._session.execute(
            sql_delete(TaskState).where(
                TaskState.owner_type == owner_type,
                TaskState.owner_id == owner_id,
            )
        )
        await self._session.commit()
        return result.rowcount

    async def get_pending_interaction_by_session(
        self, session_id: str
    ) -> Optional[dict]:
        """Return the latest pending interaction checkpoint for one chat session.

        A checkpoint is a row whose status is one of
        ``awaiting_input/interaction_consuming/interaction_failed`` and whose
        ``interaction_state`` column is non-null. This is intentionally
        session-scoped: annotation tasks carry ``session_id=NULL`` by design
        and are excluded — chat callers never receive annotation state.

        A parked row whose checkpoint JSON is corrupt is stale garbage, not
        recoverable state: no resume could ever parse it, yet the row keeps
        holding the session claim (new submissions are refused) with no
        dialog left to answer. The read self-heals by deleting the stale row
        and returning None (see ``_delete_if_checkpoint_corrupt``), so the
        caller's "nothing pending" cleanup releases the session.

        Status violations (e.g. a row with non-null ``interaction_state`` but
        ``status='completed'``) remain invariant violations surfaced as "not
        found" without recovery; the write side owns state-machine
        correctness.
        """
        if not session_id:
            return None
        result = await self._session.execute(
            select(TaskState)
            .where(
                TaskState.session_id == session_id,
                TaskState.status.in_((STATUS_AWAITING_INPUT, STATUS_INTERACTION_FAILED)),
                TaskState.interaction_state.isnot(None),
            )
            .order_by(TaskState.created_at.desc())
            .limit(1)
        )
        task = result.scalar_one_or_none()
        if not task:
            return None
        if await self._delete_if_checkpoint_corrupt(task):
            return None
        return self._parse_json(task.interaction_state)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    async def get_active_by_session(self, session_id: str) -> Optional[Dict]:
        """Return the latest active task for a session.

        Active here spans runnable, paused, and interaction recovery states.
        """
        return await self.get_active_by_owner("chat_session", session_id)

    async def get_active_annotation_reply(self, annotation_id: str) -> Optional[Dict]:
        """Return the latest active annotation reply task for an annotation."""
        return await self.get_active_by_owner("annotation", annotation_id)

    async def get_active_by_owner(self, owner_type: str, owner_id: str) -> Optional[Dict]:
        """Return latest active task for a logical owner.

        Active here spans runnable and paused states: queued, running,
        awaiting_input/interaction_consuming/interaction_failed, and
        cancelling (wind-down in progress). A recoverable row whose checkpoint
        JSON is corrupt is stale garbage
        (``_delete_if_checkpoint_corrupt``): it is deleted and the read
        re-runs, so a coexisting runnable row (a resume's queued claim)
        still gates the owner instead of the read reporting a free owner.
        """
        if not owner_type or not owner_id:
            return None
        task = await self._latest_active_row(owner_type, owner_id)
        if task is not None and await self._delete_if_checkpoint_corrupt(task):
            task = await self._latest_active_row(owner_type, owner_id)
        return self._to_dict(task) if task else None

    async def _latest_active_row(
        self, owner_type: str, owner_id: str,
    ) -> Optional[TaskState]:
        result = await self._session.execute(
            select(TaskState)
            .where(
                and_(
                    TaskState.owner_type == owner_type,
                    TaskState.owner_id == owner_id,
                    TaskState.status.in_([
                        STATUS_QUEUED, STATUS_RUNNING,
                        STATUS_AWAITING_INPUT, STATUS_INTERACTION_CONSUMING,
                        STATUS_INTERACTION_FAILED, STATUS_CANCELLING,
                    ]),
                )
            )
            # created_at has second precision; updated_at breaks ties between
            # rows created within the same second (e.g. a parked checkpoint
            # and its resume's queued row).
            .order_by(
                TaskState.created_at.desc(),
                TaskState.updated_at.desc(),
            )
            .limit(1)
        )
        return result.scalar_one_or_none()

    async def _delete_if_checkpoint_corrupt(self, task: TaskState) -> bool:
        """Delete a parked row whose checkpoint JSON is corrupt; True if so.

        Corrupt = stale: the checkpoint can never be parsed by any reader,
        but the interaction row keeps holding its owner's claim — the
        owner is stuck with no dialog to answer and no resume that would
        clear the row. Deleting it is the recovery path that releases the
        owner. Rows in any other state, and parked rows with a parseable or
        empty checkpoint, are left untouched.
        """
        if task.status not in (STATUS_AWAITING_INPUT, STATUS_INTERACTION_FAILED) or not task.interaction_state:
            return False
        try:
            json.loads(task.interaction_state)
            return False
        except (json.JSONDecodeError, TypeError):
            logger.warning(
                "Deleting task %s: its interaction checkpoint JSON is "
                "corrupt and can never resume; the owner's claim is released.",
                task.task_id,
            )
            await self._session.execute(
                sql_delete(TaskState).where(TaskState.task_id == task.task_id)
            )
            await self._session.commit()
            return True

    async def get_by_id(self, task_id: str) -> Optional[Dict]:
        """Return a task state dict by task_id, or None."""
        result = await self._session.execute(
            select(TaskState).where(TaskState.task_id == task_id)
        )
        task = result.scalar_one_or_none()
        if not task:
            return None
        return self._to_dict(task)

    def _to_dict(self, task: TaskState) -> Dict:
        return {
            "task_id": task.task_id,
            "session_id": task.session_id,
            "owner_type": task.owner_type,
            "owner_id": task.owner_id,
            "status": task.status,
            "task_type": task.task_type,
            "error": task.error,
            "interaction_state": self._parse_json(task.interaction_state),
            "created_at": task.created_at,
            "updated_at": task.updated_at,
        }

    @staticmethod
    def _parse_json(value: Optional[str]) -> Optional[dict]:
        if not value:
            return None
        try:
            return json.loads(value)
        except (json.JSONDecodeError, TypeError):
            return None
